edc.participant.id=did:web:bitds.eu:participant:provider-base:public:did
edc.hostname=localhost
edc.dsp.callback.address=http://localhost:19194/protocol
web.http.port=19191
web.http.path=/api

web.http.management.port=19193
web.http.management.path=/management
web.http.management.auth.type=tokenbased
web.http.management.auth.key=managementApiKeyProviderBase
web.http.management.auth.context=management-api

web.http.protocol.port=19194
web.http.protocol.path=/protocol
edc.transfer.proxy.token.signer.privatekey.alias=private-key
edc.transfer.proxy.token.verifier.publickey.alias=public-key

web.http.public.port=19291
web.http.public.path=/public
web.http.control.port=19192
web.http.control.path=/control
web.http.version.port=19195
web.http.version.path=/version
edc.dataplane.api.public.baseurl=http://localhost:19291/public

org.bitds.edc.provider.validation.asset.schema.path=asset-schema-dcat.json
org.bitds.edc.provider.validation.dataset.schema.path=dataset-schema-dcat.json

# configuration PostgreSQL DB
edc.datasource.default.name=default
edc.datasource.default.user=postgres
edc.datasource.default.password=postgres
edc.datasource.default.url=jdbc:postgresql://postgresql-ds:5432/edc_provider-base
edc.sql.schema.autocreate=true

# Service Provider
org.bitds.edc.service.dataservice.credentials.default={\"description\": \"Default. Please check the documentation in the homepage\", \"url\": \"https://myservice.com/mydashboard\", \"user\": \"customer\", \"password\": \"defaultpass\"}

# catalog
org.bitds.edc.provider.extension.dcat.based.api.catalog.title=EDC Provider Base Catalog
org.bitds.edc.provider.extension.dcat.based.api.catalog.description=EDC Provider Base Catalog with DCAT format
org.bitds.edc.provider.extension.dcat.based.api.catalog.publisher.name=EDC Provider Base Catalog Publisher

#eIDAS
edc.participant.eidas.url=http://localhost:19191/api/vp_token
edc.participant.eidas=/identity/vptoken.txt
edc.bitds.eidas.verifier.mdoc.url=https://testeidas.loguea.es/api/utilities/validations/msoMdoc/deviceResponse

# identity
edc.participant.registry.url=http://localhost:39191/api/
edc.participant.claims=provider-base/resources/identity/claims.json
edc.participant.private.key=provider-base/resources/identity/ed25519_private.pem
edc.participant.public.key=provider-base/resources/identity/ed25519_public.pem
